// Generates src/data/tower.ts from tower-reqs.txt by greedy-matching
// against item names from items.json. Logs anything unmatched so they
// can be verified (e.g. items not yet in items.json).
//
// Usage: node scripts/gen-tower.js

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'tower-reqs.txt');
const ITEMS = path.join(ROOT, 'src/data/items.json');
const OUT = path.join(ROOT, 'src/data/tower.ts');

const items = JSON.parse(fs.readFileSync(ITEMS, 'utf8'));
// Map lowercase name -> canonical name. Sort keys by length desc for greedy.
const byLower = new Map(items.map((i) => [i.name.toLowerCase(), i.name]));
const namesByLen = [...byLower.keys()].sort((a, b) => b.length - a.length);

// Greedy-match the longest known item name as a prefix of `s` (case-insensitive,
// word-boundary aware). Returns { name, end } or null.
function matchPrefix(s) {
  const lower = s.toLowerCase();
  for (const candidate of namesByLen) {
    if (lower.startsWith(candidate)) {
      const next = lower[candidate.length];
      if (next === undefined || next === ' ') {
        return { name: byLower.get(candidate), end: candidate.length };
      }
    }
  }
  return null;
}

const unmatched = [];

// Parse a line of items. If `duplicated`, each item appears twice in a row.
function parseItems(line, duplicated, ctx) {
  const cleaned = line.replace(/[,&]/g, ' ').replace(/\s+/g, ' ').trim();
  let s = cleaned;
  const found = [];
  let unknownBuf = []; // accumulated unmatched words

  const flushUnknown = () => {
    if (unknownBuf.length === 0) return;
    let name = unknownBuf.join(' ');
    if (duplicated) {
      // For section-1 lines each item appears twice: "X X" or "X Y X Y".
      // The buffered unknown contains both copies — halve it.
      if (unknownBuf.length % 2 === 0) {
        const half = unknownBuf.length / 2;
        const a = unknownBuf.slice(0, half).join(' ');
        const b = unknownBuf.slice(half).join(' ');
        if (a === b) name = a;
      }
    }
    unmatched.push({ name, ctx });
    found.push(name);
    unknownBuf = [];
  };

  while (s.length > 0) {
    const m = matchPrefix(s);
    if (m) {
      flushUnknown();
      found.push(m.name);
      s = s.slice(m.end).trimStart();
      if (duplicated) {
        const lower = s.toLowerCase();
        const cand = m.name.toLowerCase();
        if (lower.startsWith(cand)) s = s.slice(cand.length).trimStart();
      }
      continue;
    }
    const sp = s.indexOf(' ');
    if (sp === -1) { unknownBuf.push(s); s = ''; }
    else { unknownBuf.push(s.slice(0, sp)); s = s.slice(sp + 1); }
  }
  flushUnknown();
  return found;
}

const text = fs.readFileSync(SRC, 'utf8');
const lines = text.split('\n');

const out = {}; // canonical name -> { level, type }

let section = 1;
let i = 0;
while (i < lines.length) {
  const line = lines[i];
  if (line.startsWith('After T300')) { section = 2; i++; continue; }
  if (section === 1) {
    const m = line.match(/^(\d+)\s*$/);
    if (m && lines[i + 1]) {
      const level = parseInt(m[1], 10);
      const itemsLine = lines[i + 1];
      const found = parseItems(itemsLine, true, `L${level} mega`);
      for (const n of found) out[n] = { level, type: 'mega' };
      i += 2;
      continue;
    }
    i++;
  } else {
    // Section 2: tab-separated "level\tgms\tmms"
    const cols = line.split('\t');
    const lvl = parseInt(cols[0], 10);
    if (Number.isFinite(lvl) && lvl >= 301) {
      const gms = parseItems(cols[1] || '', false, `L${lvl} grand`);
      const mms = parseItems(cols[2] || '', false, `L${lvl} mega`);
      for (const n of gms) out[n] = { level: lvl, type: 'grand' };
      for (const n of mms) out[n] = { level: lvl, type: 'mega' };
    }
    i++;
  }
}

const sorted = Object.keys(out).sort();
const body = sorted.map((k) => `  "${k.replace(/"/g, '\\"')}": { level: ${out[k].level}, type: "${out[k].type}" },`).join('\n');

const ts = `// Generated by scripts/gen-tower.js from tower-reqs.txt.
// "mega" = Mega Mastery required (levels 201-300 + select 301+ levels).
// "grand" = Grand Mastery required (levels 301+).

export interface TowerRequirement {
  level: number;
  type: "mega" | "grand";
}

export const TOWER_REQUIREMENTS: Record<string, TowerRequirement> = {
${body}
};
`;

fs.writeFileSync(OUT, ts);
console.log(`wrote ${sorted.length} tower entries to ${path.relative(ROOT, OUT)}`);
if (unmatched.length) {
  console.log(`\n${unmatched.length} unmatched (not in items.json):`);
  for (const u of unmatched) console.log(`  ${u.ctx}: "${u.name}"`);
}
